
modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="http://"

[[mods]] #mandatory

modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
authors=" Livid | SadBo1 "
description='''
Basic Block
'''

[[dependencies.examplemod]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"         # BEFORE | AFTER | NONE
    side="BOTH"             # BOTH | CLIENT | SERVER

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
